spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_flyway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  flyway:
    locations:
      - classpath:db